### ISSUE TITLE
Support of Copernicus Sentinel 2

### ISSUE THREAD

**Issue by dpoursanidis** [SMByC/CCD-Plugin#1]
Hi,

Great work! A nice tool for easy data retrieval.
Any chance to be able to port other available in GEE datasets such as Copernicus Sentinel 2 or Planet Cubesat?

Best

Dimitris

**Comment by XavierCLL** [comment]
Hi @dpoursanidis that's a good idea for a future feature to include, thanks!

**Comment by XavierCLL** [comment]
Hi @dpoursanidis 

The new version 23.7 include Sentinel 2, check it out!
