### ISSUE TITLE
Unable to connect using the latest version (24.6) CCD plugin in QGIS

### ISSUE THREAD

**Issue by lsrrwnmg** [SMByC/CCD-Plugin#13]
When I use the latest version (24.6) of the CCD plugin in QGIS, the following error message appears:
Your application is authenticating by using local Application Default Credentials. The earthengine.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .
But I can log in to the GEE platform normally（ https://code.earthengine.google.com/ ）

**Comment by XavierCLL** [comment]
Hi @lsrrwnmg 

Does the google earth engine Qgis plugin work correctly? Open the python console in Qgis and try to run some [examples](https://github.com/gee-community/qgis-earthengine-plugin/tree/master/examples). Else, try to [reset your authentication settings](https://github.com/gee-community/qgis-earthengine-plugin?tab=readme-ov-file#how-to-reset-your-authentication-settings) and try again with a GEE example. The CCD plugin needs GEE to work correctly on your computer not on the platform. Let me know how does it goes.

**Comment by XavierCLL** [comment]
@lsrrwnmg any news about that?

**Comment by lsrrwnmg** [comment]
Hello XavierCLL! Thank you very much for your answer. I tried it according to your suggestion. First, enter "import ee" in the Python Console of QGIS, and then a website pops up. I logged in to my GEE account. After clicking Allow, the webpage shows "QGIS Google Earth Engine plugin authentication finished successfully.", but when I return to QGIS, an error message appears:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\code.py", line 90, in runcode
exec(code, self.locals)
File "<input>", line 1, in <module>
File "C:\Users/Sunshine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 44, in __wrapping_ee_import__
if authenticate(ee=_module_):
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/Sunshine/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_auth.py", line 84, in authenticate
response = urllib.request.urlopen(ee.oauth.TOKEN_URI, data).read().decode()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 215, in urlopen
return opener.open(url, data, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 515, in open
response = self._open(req, data)
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 532, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 492, in _call_chain
result = func(*args)
^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 1392, in https_open
return self.do_open(http.client.HTTPSConnection, req,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\urllib\request.py", line 1347, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error Remote end closed connection without response>
I guess there might be something wrong with the VPN or proxy I'm using, but I've tried 3 different VPNs and still got the same error.

**Comment by XavierCLL** [comment]
Yeah, it looks like an internet problem, a different issue. There are some [instructions if you are behind a proxy](https://github.com/gee-community/qgis-earthengine-plugin?tab=readme-ov-file#are-you-through-a-proxy) , but the best is not to use anything or just a VPN, not a proxy. [](url)

**Comment by XavierCLL** [comment]
Closing it for now because it is a not plugin issue, although it is good to know if you find a workaround to fix the connection issue
