### ISSUE TITLE
Plot download directory

### ISSUE THREAD

**Issue by WangariKimotho** [SMByC/CCD-Plugin#2]
This plugin is very useful and I also love it's dynamic output using plotly. I would however also love to download the plots and choose the directory where they are saved myself. Currently I am getting a toast message saying saved as "newplot.png" but cannot locate where. 

Using linux.

 Thanks

**Comment by XavierCLL** [comment]
Hi @WangariKimotho, 

I'm glad you like the plugin. Yes, I'm aware of that issue, that happens in any OS, there's a problem between QtWebView and Plotly, maybe a permission problem, but to be sincere, I have no idea how to fix it right now (or time to check it deeply), for now the only way it using a screenshot tool for that. Or the other idea that occurs to me is, every time the plugin creates a plot it saves the HTML (ploty) file in the temp directory (in linux /tmp, a random folder like /tmp/tmpv8l7t_ps/) and then opens the HTML in a web browser.

Xavier

**Comment by WangariKimotho** [comment]
I see, I actually changed the plot parameter from auto_open=False to auto_open=True, then saved the rendered html to a non-temporary location. works for now. Thanks

**Comment by XavierCLL** [comment]
Maybe a good idea is to add an icon to open the plot in an external web browser...

**Comment by XavierCLL** [comment]
Fixing this issue in the commit 42aa452bfd97f25845177aaa8eae27eb69fca34f in the develop branch with a button to open the plot in the web browser
