### ISSUE TITLE
Allow more decimals places when setting Chi-square

### ISSUE THREAD

**Issue by danielm09** [SMByC/CCD-Plugin#8]
Currently, the parameter Chi-square, which can be adjusted in the "Advanced settings", only allows 2 decimals places. 
Change max number of decimal places.

**Comment by XavierCLL** [comment]
Thanks @danielm09, you're right, better have more decimal places in that parameter, fixed.

**Comment by danielm09** [comment]
I think it was fixed in the GUI code, but it is not available when people download the plugin from the QGIS repo. Maybe it needs to update something in the QGIS repo side to download the lastest version of this repo?

**Comment by XavierCLL** [comment]
Hi @danielm09 yeah because I didn't upload a new version with that fix, I have just done it, v23.11

**Comment by danielm09** [comment]
@XavierCLL Thanks!
